name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:1.13.7
    steps:
    # - name: Set up Go 1.x
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: ^1.13
    #   id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get github.com/dustinkirkland/golang-petname

    - name: Test
      run: |
        cd src/main
        chmod +x test-mr.sh
        ./test-mr.sh
